# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Finder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FontAwesome.swift'
  pod 'UIColor_Hex_Swift'
  pod 'SideMenu'
  pod 'DLRadioButton'
  pod 'IQKeyboardManagerSwift'
  pod 'RangeSeekSlider'
  pod 'CollectionViewWaterfallLayout'
  pod 'DropDown'
  pod 'ImageSlideshow'
  pod 'SDWebImage'
  pod 'JSQSystemSoundPlayer'

  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  pod 'Alamofire'
  pod 'DKImagePickerController'
  pod 'SwiftKeychainWrapper'
end
